Repository WordPress/wporg-news-2021, pull requests merged in 2022-01, with the labels that each got.

#195 Fix local nav bar visual elements
  source/wp-content/themes/wporg-news-2021/sass/components/_local-header.scss
Labels: theme

#201 Local Header: Add Top-Border to Dark Variant
  source/wp-content/themes/wporg-news-2021/sass/components/_local-header.scss
Labels: theme

#236 Homepage: Fix horizontal scrolling
  source/wp-content/themes/wporg-news-2021/sass/page/front-page/_front-page.scss
  source/wp-content/themes/wporg-news-2021/sass/page/front-page/_people-of-wordpress.scss
Labels: bug

#235 Alignments: Add negative margins to .alignfull
  source/wp-content/themes/wporg-news-2021/sass/base/_elements.scss
  source/wp-content/themes/wporg-news-2021/sass/base/_layout.scss
Labels: bug

#237 Page Template: Add edge spacing padding to pages
  source/wp-content/themes/wporg-news-2021/sass/post/_single.scss
Labels: bug

#233 Categories archives: Hide the decorative archive title from screen readers
  source/wp-content/themes/wporg-news-2021/block-templates/category.html
  source/wp-content/themes/wporg-news-2021/sass/page/_categories.scss
Labels: accessibility

#249 Adjust vertical position of query title mask
  source/wp-content/themes/wporg-news-2021/sass/components/_query-title-banner.scss
Labels: bug

#250 Modularize components/_local-header.scss
  source/wp-content/themes/wporg-news-2021/sass/base/_layout.scss
  source/wp-content/themes/wporg-news-2021/sass/components/_local-header.scss
  source/wp-content/themes/wporg-news-2021/sass/components/local-header/_breadcrumbs.scss
  source/wp-content/themes/wporg-news-2021/sass/components/local-header/_categories.scss
  source/wp-content/themes/wporg-news-2021/sass/components/local-header/_local-header.scss
  source/wp-content/themes/wporg-news-2021/sass/style.scss
Labels: enhancement
